### ISSUE TITLE
次回 2/18(水)13:00- までにやること

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#95]
* indigo, (Ubuntu14.04)を入れる。
* グリッパーの機構を考える。また材料を調達。
* virtual_force_publisherの準備。 (物体を判別するため)
* https://github.com/start-jsk/2014-semi/issues/93 @iory 
* https://github.com/start-jsk/2014-semi/issues/92 @wkentaro

**Comment by Tnoriaki** [comment]
ubuntuを14.04にアップグレードしたのですが、ネット接続ができなくなりました。
有線LAN、無線LANどちらも右上の扇形アイコンでは接続できているんですが、
ブラウザなどを開いて確認すると接続できていない状態になっています。
どなたか対処方法を教えていただけると幸いです．．．

**Comment by jiangjun0105** [comment]
![image](https://cloud.githubusercontent.com/assets/8521008/6201710/db4411e6-b4fc-11e4-9e06-b5895c258349.png)
どこにこのようなものがかえる？
I ever played with it when I was a child. It is made of soft and sticky material which I think may be suitable for the vacuum cup.

**Comment by k-okada** [comment]
Hello All,

For those of you receiving a shelf-kit palette this month (and those of you interested in seeing more details of the shelf design), here are the build instructions you should follow when assembling your shelf. Please read them in their entirety before assembling the kit, since if you make a mistake we will not be able to send you replacement parts.

https://www.scribd.com/doc/254585504/APC-Shelf-Assembly-Instructions

Thanks,
Joe Romano
